# Generated by Django 2.2 on 2020-02-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200225_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(default='-пусто-', max_length=100, unique=True),
        ),
    ]
