# Generated by Django 2.2 on 2020-02-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200225_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(default='-пусто-', max_length=200),
        ),
    ]
